### ISSUE TITLE
Attribute Embedding for low record projects run into an error

### ISSUE THREAD

**Issue by JWittmeyer** [code-kern-ai/refinery-embedder#2]
Traceback:
```
Traceback (most recent call last):
  File "/program/./controller.py", line 295, in run_encoding
    for pair in generate_batches(
  File "/program/./controller.py", line 63, in generate_batches
    yield {"record_ids": record_batch, "embeddings": next(embedding_batches)}
  File "/usr/local/lib/python3.9/site-packages/embedders/classification/reduce.py", line 44, in _reduce
    self.reducer.fit(embeddings_training_flattened)
  File "/usr/local/lib/python3.9/site-packages/sklearn/decomposition/_pca.py", line 408, in fit
    self._fit(X)
  File "/usr/local/lib/python3.9/site-packages/sklearn/decomposition/_pca.py", line 483, in _fit
    return self._fit_full(X, n_components)
  File "/usr/local/lib/python3.9/site-packages/sklearn/decomposition/_pca.py", line 501, in _fit_full
    raise ValueError(
ValueError: n_components=64 must be between 0 and min(n_samples, n_features)=30 with svd_solver='full'
```

Currently the creation fails without any meaningful notification. Atm, I think a notification about the min size would suffice since labeling of < 64 record project are pretty uncommon.

**Comment by FelixKirsch** [comment]
An alternative solution would be to skip the PCA for projects with less than 64 records.
